#!/bin/bash
# Install Icinga2 on Debian 9
# if wget is not working do a ///  apt-get install ca-certificates
# wget https://raw.githubusercontent.com/syswombat/batch/master/inst-icinga2 -O - > /tmp/inst-icinga2
# chmod +x /tmp/inst-icinga2
# run with inst-icinga2
# This file will run on my Network
#################################################################################

# Change IP

apt update -y
apt upgrade -y
apt install -y bash-completion
apt install -y vim-nox
echo set number >> ~/.vimrc
apt install -y net-tools


# change Name
hostnamectl set-hostname icinga2-01

apt install -y apache2 
apt install -y libapache2-mod-php7.0 
apt install -y php7.0-xml
apt install -y php7.0-opcache
apt install -y php7.0-xml 
apt install -y php7.0-mbstring 
apt install -y php7.0-json 
apt install -y php7.0-curl 
apt install -y php7.0-ldap 
apt install -y php7.0-cli 
apt install -y php7.0-gd 
apt install -y php7.0-intl 
apt install -y php7.0-readline 
apt install -y php7.0-pgsql
apt install -y mariadb-server 
apt install -y mariadb-client 
apt install -y php7.0-mysql

systemctl enable apache2 mariadb
systemctl start apache2 mariadb
systemctl status apache2 mariadb

apt install -y python-pip
# apt install -y python3-pip
